version: ~> 1.0

# only run for: merge commits, releases and pull-requests
if: type != push OR branch = master OR branch =~ /^\d+\.\d+\.\d+(-.*)?$/

stages:
  - name: validate
  - name: test
  - name: deploy
    if: branch =~ /^\d+\.\d+\.\d+(-.*)?$/

os: osx
language: swift
osx_image: xcode11.2

env:
  global:
    - TEST_ENV_VAR=varval

jobs:
  include:
    - stage: validate
      name: Check if Linux tests are synced
      install: swift test --generate-linuxmain
      script: git diff --exit-code

    - &macos_test
      stage: test
      name: macOS / Swift 5.1.2
      before_script: swift build
      script: swift test --parallel
    - <<: *macos_test
      name: macOS / Swift 5.1
      osx_image: xcode11
    
    - name: Linux / Swift 5.1
      os: linux
      env: SWIFT_VERSION=5.1
      language: generic
      install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script: swift test --parallel
    
    - stage: deploy
      name: Create documentation
      install: gem install jazzy
      script: |
        jazzy --config .github/jazzy.yml \
          --module-version $TRAVIS_TAG \
          --github_url "https://github.com/$TRAVIS_REPO_SLUG"
      deploy:
        provider: pages
        token: $GITHUB_TOKEN
        local_dir: output
        edge: true
        on:
          tags: true
